# Generated by Django 5.1.6 on 2025-02-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
