# Generated by Django 5.1.6 on 2025-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('about_me', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('graduation', models.TextField(null=True)),
                ('specialization', models.TextField(null=True)),
            ],
        ),
    ]
