# Generated by Django 5.1.6 on 2025-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='descirption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
