# Generated by Django 5.1.6 on 2025-02-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_appointment_descirption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='descirption',
            new_name='description',
        ),
    ]
