# Generated by Django 5.1.6 on 2025-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(blank=True, null=True, upload_to='models/')),
                ('type', models.TextField(blank=True, null=True)),
                ('descritpion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
