# Generated by Django 5.1.6 on 2025-06-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='if_bot',
            field=models.BooleanField(default=False),
        ),
    ]
